from pptx import Presentation
from pptx.util import Inches, Pt, Cm
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from io import BytesIO
from typing import List, Dict

class PPTService:
    def create_presentation(self, slides_data: List[Dict], topic: str) -> BytesIO:
        """
        Creates a professional PowerPoint presentation with custom styling.
        """
        prs = Presentation()
        
        # Design Theme Colors
        # Modern Blue Theme
        PRIMARY_COLOR = RGBColor(41, 128, 185)   # Beliz Hole Blue
        ACCENT_COLOR = RGBColor(52, 152, 219)    # Peter River Blue
        TEXT_COLOR = RGBColor(44, 62, 80)        # Midnight Blue
        BG_COLOR = RGBColor(236, 240, 241)       # Clouds (Light Grey/White)
        WHITE = RGBColor(255, 255, 255)
        
        # 1. Title Slide (Custom Layout)
        slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank layout
        
        # Full Blue Background for Title
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = PRIMARY_COLOR
        
        # Decor: Decorative Line
        shape = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, Inches(0), Inches(4.2), prs.slide_width, Inches(0.1)
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = WHITE
        shape.line.fill.background()
        
        # Title Text
        left = Inches(1)
        top = Inches(2.5)
        width = Inches(8)
        height = Inches(2)
        
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.text = topic
        p = tf.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        p.font.size = Pt(54)
        p.font.bold = True
        p.font.color.rgb = WHITE
        
        # Subtitle
        top = Inches(4.5)
        txBox = slide.shapes.add_textbox(left, top, width, Inches(1))
        tf = txBox.text_frame
        tf.text = "Generated by AI Study Buddy"
        p = tf.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        p.font.size = Pt(20)
        p.font.color.rgb = RGBColor(220, 220, 220)
        
        # 2. Content Slides
        for idx, slide_data in enumerate(slides_data):
            slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank
            
            # Header Bar
            header_height = Inches(1.3)
            shape = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, header_height
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = PRIMARY_COLOR
            shape.line.fill.background()
            
            # Logo/Brand text in header (top right)
            brand_box = slide.shapes.add_textbox(Inches(7.5), Inches(0.4), Inches(2), Inches(0.5))
            brand_tf = brand_box.text_frame
            brand_p = brand_tf.paragraphs[0]
            brand_p.text = "AI Study Buddy"
            brand_p.alignment = PP_ALIGN.RIGHT
            brand_p.font.size = Pt(12)
            brand_p.font.color.rgb = RGBColor(200, 200, 255)
            
            # Slide Title
            left = Inches(0.5)
            top = Inches(0.3)
            width = Inches(8)
            height = Inches(0.8)
            
            txBox = slide.shapes.add_textbox(left, top, width, height)
            tf = txBox.text_frame
            tf.text = slide_data.get("title", "Untitled")
            p = tf.paragraphs[0]
            p.font.size = Pt(32)
            p.font.bold = True
            p.font.color.rgb = WHITE
            p.alignment = PP_ALIGN.LEFT
            
            # Content Box (Body)
            left = Inches(0.5)
            top = Inches(1.8)
            width = Inches(9)
            height = Inches(5)
            
            txBox = slide.shapes.add_textbox(left, top, width, height)
            tf = txBox.text_frame
            tf.word_wrap = True
            
            points = slide_data.get("points", [])
            for point in points:
                p = tf.add_paragraph()
                p.text = "• " + point
                p.font.size = Pt(22)
                p.font.color.rgb = TEXT_COLOR
                p.space_after = Pt(14)
                p.level = 0
                
            # Footer: Slide Number
            left = Inches(8.8)
            top = Inches(7.1)
            width = Inches(0.8)
            height = Inches(0.4)
            txBox = slide.shapes.add_textbox(left, top, width, height)
            tf = txBox.text_frame
            p = tf.paragraphs[0]
            p.text = f"{idx + 1}"
            p.alignment = PP_ALIGN.RIGHT
            p.font.size = Pt(12)
            p.font.color.rgb = RGBColor(127, 140, 141)
            
            # Decorative Bottom Strip
            shape = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE, 0, Inches(7.4), prs.slide_width, Inches(0.1)
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = ACCENT_COLOR
            shape.line.fill.background()
            
            # Add Speaker Notes
            if "notes" in slide_data:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = slide_data["notes"]
                
        # Save
        output = BytesIO()
        prs.save(output)
        output.seek(0)
        return output
